// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnMQX3gC1qrWlb7H-SjhPsizINgYCK6nk',
    appId: '1:1083997076744:web:982e40cd1560fb51dd80bd',
    messagingSenderId: '1083997076744',
    projectId: 'makernote-b5e60',
    authDomain: 'makernote-b5e60.firebaseapp.com',
    storageBucket: 'makernote-b5e60.appspot.com',
    measurementId: 'G-X5BW4HV6R7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVqo8l3X-JMKTMhCEyc6pZMIDKe96V8m4',
    appId: '1:1083997076744:android:446f03d0d3b3d1abdd80bd',
    messagingSenderId: '1083997076744',
    projectId: 'makernote-b5e60',
    storageBucket: 'makernote-b5e60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGn24NpAoKdGUO7-Q8zhNrNQOJ5yLn6I',
    appId: '1:1083997076744:ios:dcc38cb2f82001a3dd80bd',
    messagingSenderId: '1083997076744',
    projectId: 'makernote-b5e60',
    storageBucket: 'makernote-b5e60.appspot.com',
    iosClientId:
        '1083997076744-5ves3q4r3ff8id2eg94q27b0afhialec.apps.googleusercontent.com',
    iosBundleId: 'com.tackledinnovationltd.makernote',
  );
}
